# Generated by Django 5.2.12 on 2026-03-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_notes_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notes",
            name="likes",
        ),
        migrations.AddField(
            model_name="notes",
            name="likes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
